events { worker_connections 1024; }

http {
    client_max_body_size 0;

    types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
        text/html html htm;
        text/css css;
        application/javascript js;
        image/png png;
        image/jpeg jpg jpeg;
        image/gif gif;
        image/svg+xml svg;
        application/json json;
    }

    upstream api { server api:8080; }
    upstream frontend { server frontend:80; }
    upstream minio { server minio:9000; }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }

        location /hangfire {
            proxy_pass http://api;
            proxy_set_header Host $host;
        }

        location /hls/ {
            proxy_pass http://minio/streaming/conteudo/;
            add_header Cache-Control "public, max-age=31536000";
            add_header Access-Control-Allow-Origin *;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
